name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          max_ctu_depth: 4
          skip_preprocessor: enable
          check_library: disable
          inconclusive: enable
          inline_suppression: disable
          platform: disable
        
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main


